# Generated by Django 2.2.10 on 2020-03-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="picture",
            field=models.ImageField(upload_to="src/media/author/"),
        ),
    ]
