# Generated by Django 2.2.10 on 2020-03-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="hero_image",
            field=models.ImageField(max_length=255, upload_to="src/media/hero_images/"),
        ),
    ]
